### PR TITLE
Enchantress on map; fixes #20

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @misiokles,

This PR fixes the perspective issue of the _Enchantress_ creature on the map. The shadows are on the wrong way but it's better than nothing.

@by003, have you noticed that the idle animation of _Sibyl_ on the battle screen have been animated? Can you update the _Enchantress_ creature animation?

### CODE REVIEW

**Comment by by003** [comment]
It have already updated.

https://github.com/user-attachments/assets/3f32f691-304d-480c-8bd6-6f7c728dfb4e

**Comment by Fabrice-TIERCELIN** [comment]
Not the _Mouse Over_ animation, @by003, the _Standing_ animation. I have improved both.

**Comment by by003** [comment]
@Fabrice-TIERCELIN I have seen new standing animation,it has already been updated here.
[CFar10.zip](https://github.com/user-attachments/files/16424885/CFar10.zip)

**Comment by Fabrice-TIERCELIN** [comment]
Cool, @by003! I have added this improvement to this PR.

**Comment by Fabrice-TIERCELIN** [comment]
@by003, you had changed something on the _Sibyl_ animation on the map and it breaks something: the first image hasn't the same contrast as the others. I have restored the animation.

The problem is that the same problem occurs on the _Enchantress_ animation on map. It would be great if you can fix it.

**Pull request merged**
