### PR TITLE
Create a new town theme

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @misiokles,

This PR changes the theme of the town.

The music has been made with _Udio_ with the prompt `Classical music, Soundtrack, Score, Instrumental, 160 bpm, fairy tale, princess, serenity`.

### CODE REVIEW

**Comment by Fabrice-TIERCELIN** [comment]
Re @misiokles,

Are there town mods in [your space](https://github.com/misiokles?tab=repositories) that you would release if the town theme was better?

**Comment by misiokles** [comment]
They are not my mods, only my collection of abandonned  mods (mostly). I just gather them, not planning to do with them anything :)

**Comment by by003** [comment]
Hello. I think this theme is more suitable for a terrain, not for town. 
Maybe try to make a town theme.

**Comment by by003** [comment]
I suggest using harp or lyre elements to remake it.

**Comment by Fabrice-TIERCELIN** [comment]
OK, here are 4 new themes with harp, from _"more harp"_ to _"more cinematic classical"_:
[theme1.webm](https://github.com/vcmi-mods/fairy-town/assets/20668759/53d766ef-2307-45b6-8dcb-6f7978ac0830)
[theme2.webm](https://github.com/vcmi-mods/fairy-town/assets/20668759/b8a7893e-7ab0-4311-9648-e5cc1e98aa1e)
[theme3.webm](https://github.com/vcmi-mods/fairy-town/assets/20668759/8d19a134-7bce-4638-b784-bad69ae4e873)
[theme4.webm](https://github.com/vcmi-mods/fairy-town/assets/20668759/2a7ae8a3-75b0-42bb-90be-3acc454a7d6a)

I can rework theme by modifying the start or the end (not the middle). I can create tons of tracks if needed.

**Comment by by003** [comment]
I think theme 4 is better, but I still suggest to add female choir and make it not very soothing. 
A soothing tune only fits the terrain background.

**Comment by Fabrice-TIERCELIN** [comment]
Hi @by003,

Here is a track with female voice, harp and intensity variation:
[theme5.webm](https://github.com/vcmi-mods/fairy-town/assets/20668759/80bb3192-c3c0-4978-a438-92cd844a04a1)

**Comment by by003** [comment]
That's great. So can you cover it to ogg or mp3? And what's the name of this theme?

**Comment by Fabrice-TIERCELIN** [comment]
I have converted it into `ogg` [here](https://github.com/Fabrice-TIERCELIN/fairy-town/blob/theme/fairy-town/content/Music/factions/Whispers_of_Twilight.ogg). The branch have been updated with this theme. And the title is _Whispers of Twilight_.

**Comment by by003** [comment]
>  And the title is _Whispers of Twilight_.

Can you add chant element in this theme? Similar like Preserve theme in HoMM4.

**Comment by Fabrice-TIERCELIN** [comment]
Here is a song with harp:
[theme6.webm](https://github.com/vcmi-mods/fairy-town/assets/20668759/d602eb99-fa20-44bb-b808-aba844dabf83)

Lyrics:

A whispered breeze
Through the enchanted trees
Guides her where the fairies play
In moonlit seas
Where hearts find e'er release
And wishes bloom in night
In the moon's embrace
Where dreams of magic trace
A princess in a golden glow
A harp's sweet grace
Her kingdom's lace
As night turns into dawn
In a garden fair
With blossoms in her hair
She dances light as morning dew
Her laughter rare
Enchantments in the air
Each step a story true
With starlight's wink
On golden rings of pink
She spins beneath celestial skies
In a castle grand
Where silver bells command
The melodies of ancient times

**Comment by by003** [comment]
> Here is a song with harp: [theme6.webm](https://github.com/vcmi-mods/fairy-town/assets/20668759/d602eb99-fa20-44bb-b808-aba844dabf83)
> 


Very good! It seems better!
Please provide a ogg format.

**Comment by by003** [comment]
What's the name of new theme?

**Comment by Fabrice-TIERCELIN** [comment]
This track has no name 🙁

Here is the `ogg` file:
[theme6.zip](https://github.com/user-attachments/files/15526283/theme6.zip)

@misiokles, I let you choose between the theme 5 and the theme 6. For me, the theme 6 is not in the standard of HOMM3 but do as you want.

**Comment by Fabrice-TIERCELIN** [comment]
@misiokles, we need at least the reason why it's not merged. Those tracks have required lots of _Udio_ credits.

**Comment by misiokles** [comment]
Because I'm at the practice outside of my PC and town till 15th June and I don't want to merge anything from my phone without testing.

**Comment by Fabrice-TIERCELIN** [comment]
Ah OK

**Comment by Fabrice-TIERCELIN** [comment]
To share to the community.
[Enchanted Ballad ext v1.2.2_Classical music, Soundtrack, Score, Instrumental, 160 bpm, fairy tale, princess, serenity.webm](https://github.com/vcmi-mods/fairy-town/assets/20668759/619e6e33-d940-4899-8c76-9c1e8d3d20aa)

**Comment by Fabrice-TIERCELIN** [comment]
To share to the community.
[Inferno s March ext v1.1.2_Orc, infernal, dynamic, volcano, 160 bpm, cinematic classical.webm](https://github.com/vcmi-mods/fairy-town/assets/20668759/d6c15c01-8b01-40cf-8d27-c7b755c918fc)

**Pull request merged**
